after_script:
- "./scripts/remove-key.sh"
before_script:
- "./scripts/add-key.sh"
before_install:
  - echo "Travis before_install"
  - chmod +x ./scripts/*.sh
branches:
  only:
  - master
  - develop
env:
  global:
  - |
      - APP_NAME="Jasonelle"
      - 'DEVELOPER_NAME="iPhone Distribution: Khor Yong Hao (C4F7EVGZVS)"'
      - PROFILE_NAME="jasonellefyhao2019"
      - IPA_NAME="jasonelle"
      - ARCHIVE_NAME="jasonelle"
      
os: osx
osx_image: xcode8
sudo: false
language: objective-c

script:
- "./scripts/build.sh"